apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads-app
  namespace: ads-dev
  labels:
    app: ads-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ads-app
  template:
    metadata:
      labels:
        app: ads-app
    spec:
      containers:
      - name: ads-container
        image: nginx:latest # À remplacer par votre image Java/React/Angular
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
