apiVersion: v1
kind: Service
metadata:
  name: ads-service
  namespace: ads-dev
spec:
  type: NodePort
  selector:
    app: ads-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # Port à 5 chiffres (plage 30000-32767)
